In [6]:
# Includes + Setup

import numpy as np 
import cv2
from matplotlib import pyplot as plt

In [7]:
def plot(bild):
    cv2.imshow('debugging',bild)
    cv2.waitKey(0)
    cv2.destroyAllWindows()

In [20]:
#Bild einlesen und ausgeben lassen

Bild_orig = cv2.imread('Bilder\sodoku1.jpg',-1)
Bild_Grau = cv2.imread('Bilder\sodoku1.jpg',0)
(tresh, Bild_bin) = cv2.threshold(Bild_Grau, 100, 200, cv2.THRESH_BINARY)
# cv2.imshow('Original',Bild)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

# cv2.imshow('Grauwerte',Bild_Grau)
# cv2.waitKey(0)
# cv2.destroyAllWindows()

hoehe, breite = Bild_Grau.shape[:2]

In [9]:
Bild_neu = cv2.erode(Bild_bin, cv2.getStructuringElement(cv2.MORPH_RECT, (3,3), (1,1)))
plot(Bild_neu)
Bild_neu = cv2.erode(Bild_neu, cv2.getStructuringElement(cv2.MORPH_RECT, (3,3), (1,1)))
plot(Bild_neu)
Bild_neu = cv2.dilate(Bild_neu, cv2.getStructuringElement(cv2.MORPH_RECT, (3,3), (1,1)))
plot(Bild_neu)
Bild_neu = cv2.dilate(Bild_neu, cv2.getStructuringElement(cv2.MORPH_RECT, (3,3), (1,1)))
plot(Bild_neu)

In [10]:
plot(Bild_neu)

In [11]:
# Canny Detektor

kanten_filter = cv2.Canny(Bild_neu, 90, 200)
plot(kanten_filter)


In [40]:
# # Hough Trafo
Bild = np.array(Bild_orig)  
print(np.min(Bild), np.max(Bild))
linien = cv2.HoughLinesP(kanten_filter,5,np.pi/180,180,minLineLength=0,maxLineGap=200)

for linie in linien:
    x1,y1,x2,y2 = linie[0]
    cv2.line(Bild,(x1,y1),(x2,y2),(0,255,0),)

plot(Bild)


6 227


In [36]:
linie = cv2.HoughLinesP(kanten,2,np.pi/180,150,minLineLength=0,maxLineGap=200)
x1,y1,x2,y2 = linie[42][0]
cv2.line(Bild,(x1,y1),(x2,y2),(0,255,0),2)

plot(Bild)

NameError: name 'kanten' is not defined

In [22]:
# ränder

index_luro = [0, 0, 0, 0]
min_links_x1 = linie[0][0][0]
min_unten_y1 = linie[0][0][1]
max_rechts_x2 = linie[0][0][2]
max_oben_y2 = linie[0][0][3]
for i in range(0,len(linie)):
    # x1 vergleichen
    if linie[i][0][0] < min_links_x1:
        min_links_x1 = linie[i][0][0]
    if linie[i][0][1] < min_unten_y1:
        min_unten_y1 = linie[i][0][1]
    if linie[i][0][2] > max_rechts_x2:
        max_rechts_x2 = linie[i][0][2]
    if linie[i][0][3] > max_oben_y2:
        max_oben_y2 = linie[i][0][3]
    



In [55]:
def kleinstes_x1(elem):
    return elem[0][0]

def kleinstes_y1(elem):
    return elem[0][1]

def groesstes_x2(elem):
    return elem[0][2]

def groesstes_y2(elem):
    return elem[0][3]

In [70]:
n = 10 
kleinste_x1 = list(linien)
kleinste_x1.sort(key=kleinstes_x1)

print(kleinste_x1)
kleinste_x1[:5]

[array([[  6, 235, 555, 235]], dtype=int32), array([[  8, 228, 560, 238]], dtype=int32), array([[ 11,  60, 292,  64]], dtype=int32), array([[ 13, 525, 172, 530]], dtype=int32), array([[ 13, 528, 572, 547]], dtype=int32), array([[ 14,  12, 555,  12]], dtype=int32), array([[ 14, 531, 189, 534]], dtype=int32), array([[ 14, 524,  34, 138]], dtype=int32), array([[ 14, 510, 575, 550]], dtype=int32), array([[ 15,  65, 556,  65]], dtype=int32), array([[ 17, 466, 568, 476]], dtype=int32), array([[ 17, 460, 568, 479]], dtype=int32), array([[ 20, 405, 560, 414]], dtype=int32), array([[ 20, 526,  47,   6]], dtype=int32), array([[ 23, 531,  41,   2]], dtype=int32), array([[ 24, 347, 564, 357]], dtype=int32), array([[ 24, 526,  42,   7]], dtype=int32), array([[ 25, 332, 564, 360]], dtype=int32), array([[ 27, 286, 562, 295]], dtype=int32), array([[ 28, 343, 564, 362]], dtype=int32), array([[ 29, 322, 564, 359]], dtype=int32), array([[ 32, 174, 558, 174]], dtype=int32), array([[ 32, 173, 554, 173]], d

[array([[  6, 235, 555, 235]], dtype=int32),
 array([[  8, 228, 560, 238]], dtype=int32),
 array([[ 11,  60, 292,  64]], dtype=int32),
 array([[ 13, 525, 172, 530]], dtype=int32),
 array([[ 13, 528, 572, 547]], dtype=int32)]

In [59]:
print(kleinste_x1)

None


In [60]:
list(linien)

[array([[ 24, 347, 564, 357]], dtype=int32),
 array([[200, 535, 203, 381]], dtype=int32),
 array([[138, 533, 157,   5]], dtype=int32),
 array([[ 23, 531,  41,   2]], dtype=int32),
 array([[ 14,  12, 555,  12]], dtype=int32),
 array([[ 15,  65, 556,  65]], dtype=int32),
 array([[382, 540, 382,   8]], dtype=int32),
 array([[ 34, 116, 557, 125]], dtype=int32),
 array([[ 32, 174, 558, 174]], dtype=int32),
 array([[  8, 228, 560, 238]], dtype=int32),
 array([[ 13, 525, 172, 530]], dtype=int32),
 array([[ 14, 531, 189, 534]], dtype=int32),
 array([[257, 536, 266,   7]], dtype=int32),
 array([[314, 538, 324,   7]], dtype=int32),
 array([[495,   9, 505, 543]], dtype=int32),
 array([[ 20, 405, 560, 414]], dtype=int32),
 array([[ 39,   2, 555,  11]], dtype=int32),
 array([[ 78, 518,  96,   4]], dtype=int32),
 array([[ 27, 286, 562, 295]], dtype=int32),
 array([[553,   9, 572, 555]], dtype=int32),
 array([[ 17, 466, 568, 476]], dtype=int32),
 array([[202, 311, 208,   6]], dtype=int32),
 array([[4